"""Pydantic v2 schemas for messages that flow through Redis Streams.

Using ``model_validate`` on the producer side guarantees the dict written to
the stream always satisfies the schema; ``model_validate`` on the consumer
side raises ``ValidationError`` on malformed messages instead of propagating
``None`` / empty strings deeper into the pipeline.
"""

from pydantic import BaseModel


class PipelineJobMessage(BaseModel):
    """Payload for a generic pipeline job written to a Redis Stream.

    The ``payload`` field carries the job inputs as a JSON-encoded string
    because Redis Streams store only string values.

    :param job_id: UUID generated by api-gateway.
    :param pipeline_id: Name of the pipeline to execute.
    :param payload: JSON-encoded ``{field: value}`` dict of job inputs.
    :param user: Subject claim of the requesting user.
    """

    job_id: str
    pipeline_id: str
    payload: str  # JSON-encoded dict[str, Any]
    user: str
