{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "moiraweave.serviceAccountName" . }}
  labels:
    {{- include "moiraweave.labels" . | nindent 4 }}
{{- end }}
{{- if and .Values.deploymentController.enabled .Values.deploymentController.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "moiraweave.deploymentController.serviceAccountName" . }}
  labels:
    {{- include "moiraweave.labels" . | nindent 4 }}
    app.kubernetes.io/component: deployment-controller
{{- end }}
